base:
  project: Mall_Segmentation
  random_state: 42

data_source:
  s3_source: source_data\Mall_Customers.csv

load_data:
  raw_dataset_csv: data\raw\mall_segmentation.csv

process_data: data\processed\Mall_Customers.csv

estimators:
  KMean:
    params:
      n_clusters: 6

model_dir: saved_models\model.joblib

reports:
  scores: reports\scores.json
  params: reports\params.json

webapp_final_model_dir: saved_models\model.joblib

trained_data: data\trained\Mall_Customers.csv

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: KMeans Clustering
  run_name: mlops
  registered_model_name: KMeansCustomerSegmentation
  remote_server_uri: http://127.0.0.1:5000
